`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Design Name: 
// Module Name: aes_pipelined_top
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

module aes_pipelined_top (
    input         clk_125mhz,     // This clock comes from the ethernet phy. By default this clock is enabled. Connect to pin K17
    input         rst_external,   // This reset from come the dip switch. Connect to G15 (SW0)
    output        temp_output
);

wire reset_n, clk, locked, data_valid_in, cipherkey_valid_in, valid_out;
wire [127:0] data_in_key, data_in, data_out;

assign temp_output = ^{data_out}; 

// 200MHz clock generation module 
clk_wiz_0 pll_inst_core (
  .clk_in1(clk_125mhz),
  .clk_out1(clk),
  .reset(rst_external),
  .locked(locked) // if locked = 1, the "clk" generated by the PLL is stable, else it is unstable
 );


//If locked = 0, put the design at reset as the clock is not ready. 
//Once the clock is ready (locked = 1) release the design out of reset
assign reset_n = locked;
aes_pipelined aes_pipelined_inst (
   .clk(clk)
  ,.reset(reset_n)
  ,.data_valid_in(data_valid_in)
  ,.cipherkey_valid_in(cipherkey_valid_in)
  ,.cipher_key(data_in_key)
  ,.plain_text(data_in)
  ,.valid_out(valid_out)
  ,.cipher_text(data_out)
);

// virtual input output module that drives data to (key and data_in) 
// and from (data_out) the AES module. 
vio_0 vio_aes (
  .clk(clk),
  .probe_in0(data_out),
  .probe_in1(valid_out),
  .probe_out0(data_valid_in),
  .probe_out1(cipherkey_valid_in),
  .probe_out2(data_in_key),
  .probe_out3(data_in)
);

endmodule
